# Generated by Django 4.1 on 2022-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ACC_ID_RES", models.CharField(max_length=32)),
                ("GENE", models.CharField(max_length=32)),
                ("PROTEIN", models.CharField(max_length=32)),
                ("Database", models.CharField(max_length=32)),
                ("KIN_ACC_ID", models.CharField(max_length=300)),
                ("KIN_GENE", models.CharField(max_length=300)),
                ("source", models.CharField(max_length=300)),
                ("disease_PSP", models.CharField(max_length=800)),
                ("disease_ptmd", models.CharField(max_length=800)),
                ("ON_FUNCTION", models.CharField(max_length=300)),
                ("ON_PROCESS", models.CharField(max_length=300)),
                ("ON_PROT_INTERACT", models.CharField(max_length=300)),
                ("ON_OTHER_INTERACT", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ACC_SITE", models.CharField(max_length=32)),
                ("index", models.IntegerField()),
            ],
        ),
    ]
